# Generated by Django 5.1.5 on 2025-02-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('medicine_photo', models.FileField(upload_to='Assets/Pharmacy/photo/')),
                ('medicine_description', models.CharField(max_length=30)),
                ('medicine_rate', models.CharField(max_length=30)),
                ('medicine_status', models.IntegerField(default=0)),
                ('Pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_pharmacy')),
            ],
        ),
    ]
