# Generated by Django 5.1.5 on 2025-02-05 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_initial'),
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.CharField(max_length=30)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_pharmacy')),
            ],
        ),
    ]
