# Generated by Django 5.1.5 on 2025-02-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_tbl_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
