# Generated by Django 5.1.5 on 2025-02-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0003_delete_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.CharField(max_length=30)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.tbl_medicine')),
            ],
        ),
    ]
