# Generated by Django 5.1.5 on 2025-03-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0004_tbl_stock'),
        ('User', '0022_delete_tbl_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stock',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='tbl_medicine',
        ),
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
