# Generated by Django 5.1.5 on 2025-03-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0017_tbl_place'),
        ('Guest', '0011_tbl_deliveryboy_tbl_user'),
        ('Pharmacy', '0005_remove_tbl_stock_medicine_delete_tbl_medicine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('medicine_photo', models.FileField(upload_to='Assets/Pharmacy/photo/')),
                ('medicine_description', models.CharField(max_length=30)),
                ('medicine_rate', models.CharField(max_length=30)),
                ('medicine_status', models.IntegerField(default=0)),
                ('Pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_pharmacy')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_category')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.CharField(max_length=30)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.tbl_medicine')),
            ],
        ),
    ]
