# Generated by Django 5.1.5 on 2025-01-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
    ]
