# Generated by Django 5.1.5 on 2025-01-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0009_tbl_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_employee',
            old_name='emp_address',
            new_name='emp_bs',
        ),
        migrations.RemoveField(
            model_name='tbl_employee',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='tbl_employee',
            name='designation_name',
        ),
        migrations.RemoveField(
            model_name='tbl_employee',
            name='emp_contact',
        ),
        migrations.RemoveField(
            model_name='tbl_employee',
            name='emp_email',
        ),
        migrations.RemoveField(
            model_name='tbl_employee',
            name='emp_name',
        ),
    ]
