# Generated by Django 5.1.5 on 2025-01-27 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_rename_emp_address_tbl_employee_emp_bs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_contact', models.CharField(max_length=30)),
                ('emp_email', models.CharField(max_length=30)),
                ('emp_address', models.CharField(max_length=30)),
                ('emp_bs', models.CharField(max_length=30)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
                ('designation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_designation')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_employee',
        ),
    ]
