# Generated by Django 5.1.5 on 2025-02-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0011_tbl_employees_delete_tbl_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
    ]
