# Generated by Django 5.1.5 on 2025-02-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0012_delete_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_email', models.CharField(max_length=30)),
                ('admin_password', models.CharField(max_length=30)),
            ],
        ),
    ]
