# Generated by Django 5.1.5 on 2025-02-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0013_tbl_admin'),
        ('Guest', '0002_delete_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
