# Generated by Django 5.1.5 on 2025-02-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0015_tbl_place'),
        ('Guest', '0006_delete_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
