# Generated by Django 5.1.5 on 2025-02-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_usercomplaint',
        ),
    ]
