# Generated by Django 5.1.5 on 2025-02-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0007_initial'),
        ('User', '0004_delete_tbl_usercomplaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_usercomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_subject', models.CharField(max_length=30)),
                ('Complaint_complaint', models.CharField(max_length=30)),
                ('Complaint_date', models.DateField(auto_now_add=True)),
                ('Complaint_status', models.IntegerField(default=0)),
                ('Complaint_replay', models.CharField(max_length=30)),
                ('Complaint_replaydate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
