# Generated by Django 5.1.5 on 2025-02-05 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_alter_tbl_deliveryboy_deliveryboy_photo_and_more'),
        ('User', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_date', models.DateField(auto_now_add=True)),
                ('Complaint_status', models.IntegerField(default=0)),
                ('Complaint_amount', models.CharField(max_length=30)),
                ('deliveryboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deliveryboy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
