# Generated by Django 5.1.5 on 2025-02-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_usercomplaint',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_usercomplaint',
        ),
    ]
