# Generated by Django 5.1.5 on 2025-02-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0009_alter_tbl_deliveryboy_deliveryboy_photo_and_more'),
        ('User', '0007_remove_tbl_usercomplaint_user_delete_tbl_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_usercomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_subject', models.CharField(max_length=30)),
                ('Complaint_complaint', models.CharField(max_length=30)),
                ('Complaint_date', models.DateField(auto_now_add=True)),
                ('Complaint_status', models.IntegerField(default=0)),
                ('Complaint_replay', models.CharField(max_length=30)),
                ('Complaint_replaydate', models.DateField(null=True)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('booking_amount', models.CharField(max_length=30)),
                ('deliveryboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deliveryboy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
