# Generated by Django 5.1.5 on 2025-02-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_usercomplaint',
        ),
    ]
